// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using netCore7api.Data;

#nullable disable

namespace netCore7api.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20230301210417_SeedVillaTableCreatedDate")]
    partial class SeedVillaTableCreatedDate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("netCore7api.Models.Villa", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Amentiy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Details")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Occupancy")
                        .HasColumnType("int");

                    b.Property<double>("Rate")
                        .HasColumnType("float");

                    b.Property<int>("Sqft")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdateDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Villas");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Amentiy = "",
                            CreatedDate = new DateTime(2023, 3, 2, 0, 4, 17, 346, DateTimeKind.Local).AddTicks(4114),
                            Details = "Ne güzel villa bunlar ilgi çekici güzel villa",
                            ImageUrl = "https://www.neyiilemeshur.com/wp-content/uploads/2014/01/bing%C3%B6l-da%C4%9Flar%C4%B1.jpg",
                            Name = "Royal Villa",
                            Occupancy = 5,
                            Rate = 200.0,
                            Sqft = 500,
                            UpdateDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 2,
                            Amentiy = "",
                            CreatedDate = new DateTime(2023, 3, 2, 0, 4, 17, 346, DateTimeKind.Local).AddTicks(4128),
                            Details = "Ne güzel villa bunlar ilgi çekici güzel villa DAHA GÜZel",
                            ImageUrl = "https://www.neyiilemeshur.com/wp-content/uploads/2014/01/bing%C3%B6l-da%C4%9Flar%C4%B1.jpg",
                            Name = "Boyal Villa",
                            Occupancy = 5,
                            Rate = 200.0,
                            Sqft = 500,
                            UpdateDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 3,
                            Amentiy = "",
                            CreatedDate = new DateTime(2023, 3, 2, 0, 4, 17, 346, DateTimeKind.Local).AddTicks(4129),
                            Details = "Ne güzel villa bunlar ilgi çekici güzel villa Daha Daha güzel",
                            ImageUrl = "https://www.neyiilemeshur.com/wp-content/uploads/2014/01/bing%C3%B6l-da%C4%9Flar%C4%B1.jpg",
                            Name = "Doyal Villa",
                            Occupancy = 5,
                            Rate = 200.0,
                            Sqft = 500,
                            UpdateDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 4,
                            Amentiy = "",
                            CreatedDate = new DateTime(2023, 3, 2, 0, 4, 17, 346, DateTimeKind.Local).AddTicks(4130),
                            Details = "Ne güzel villa bunlar ilgi çekici güzel villa Daha Daha güzel",
                            ImageUrl = "https://www.neyiilemeshur.com/wp-content/uploads/2014/01/bing%C3%B6l-da%C4%9Flar%C4%B1.jpg",
                            Name = "Doyal Villa",
                            Occupancy = 5,
                            Rate = 200.0,
                            Sqft = 500,
                            UpdateDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 5,
                            Amentiy = "",
                            CreatedDate = new DateTime(2023, 3, 2, 0, 4, 17, 346, DateTimeKind.Local).AddTicks(4131),
                            Details = "Ne güzel villa bunlar ilgi çekici güzel villa Daha Daha güzel",
                            ImageUrl = "https://www.neyiilemeshur.com/wp-content/uploads/2014/01/bing%C3%B6l-da%C4%9Flar%C4%B1.jpg",
                            Name = "Doyal Villa",
                            Occupancy = 5,
                            Rate = 200.0,
                            Sqft = 500,
                            UpdateDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
